### ISSUE TITLE
Will there be an Autoj-Bilingual-13B version?

### ISSUE THREAD

**Issue by netrookiecn** [GAIR-NLP/auto-j#12]
Thanks For Your Team's Work!

I want to make sure are you planning to provide an Autoj-Bilingual-**13B** version? with better performance in Both Chinese And English

**Comment by lockon-n** [comment]
Thanks for your interest. Major updates of Auto-J are definitely in our plan, including a larger model for bilingual usage you have mentioned.

**Comment by netrookiecn** [comment]
> Thanks for your interest. Major updates of Auto-J are definitely in our plan, including a larger model for bilingual usage you have mentioned.

Great!
