### ISSUE TITLE
您好，请问训练数据就是data目录下的数据吗

### ISSUE THREAD

**Issue by eyuansu62** [GAIR-NLP/auto-j#3]
data下就是用到的所有训练数据吗？因为我看到论文中还写到了openai summary和OpenAIWebGPT等等，这些貌似不是开源的吧？

**Comment by lockon-n** [comment]
data下就是全部的训练数据。这些训练数据是基于很多已有的公开数据集（也包括你提到的两个），使用它们的query和response进行构建的。

你提到的这两个分别是：https://huggingface.co/datasets/openai/summarize_from_feedback 和 https://huggingface.co/datasets/openai/webgpt_comparisons
