### ISSUE TITLE
Typo in post-processing

### ISSUE THREAD

**Issue by Lukeming-tsinghua** [GAIR-NLP/auto-j#7]
Looks like it should be ```return float(score_output[pos + len("Rating: [["):pos2].strip())``` here by replacing `"[["` with `"Rating: [["`.

Same issue in the example in the README file

https://github.com/GAIR-NLP/auto-j/blob/6f5a8f4ec03c5a90966446434c6e13cfd9314eda/codes/usage/example.py#L26C53-L26C53

**Comment by lockon-n** [comment]
Thanks for this comment! We have fixed the typo.
